name: pos
description: POS System Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
